---
title: "Reading Data from the Web"
author: "Zoey Zhao"
date: "10/19/2021"
output: github_document
---
```{r message=FALSE}
library(tidyverse)
library(rvest)
library(httr)
```
## NSDUH data

```{r}
url <- "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html <- read_html(url)

drug_use_html
```

Extract all tables
```{r}
drug_use_html %>%
  html_table()
```
focused on the first table
```{r}
table_marj <- 
  drug_use_html %>% 
  html_table() %>% 
  first() 

#Remove "note"
table_marj <- 
  drug_use_html %>% 
  html_table() %>% 
  first() %>%
  slice(-1) 

table_marj
```
## CSS Selectors

Get som estar wars data ...

```{r}
swm_html <- 
  read_html("https://www.imdb.com/list/ls070150896/")
```

```{r}
title_vec <- 
  swm_html %>%
  html_elements(".lister-item-header a") %>%
  html_text()

title_vec
```

```{r}
gross_rev_vec <- 
  swm_html %>%
  html_elements(".text-small:nth-child(7) span:nth-child(5)") %>%
  html_text()

runtime_vec <- 
  swm_html %>%
  html_elements(".runtime") %>%
  html_text()

swm_df <- 
  tibble(
    title = title_vec,
    rev = gross_rev_vec,
    runtime = runtime_vec)
```

## Using an API

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>% 
  content("parsed")
```

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>% 
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()
```

```{r}
brfss_smart2010 = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) %>% 
  content("parsed")
```

```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

poke[["height"]]
poke[["abilities"]]
```

???




